# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d40b60e46219bbc6efd7ea80c5085f585389c784d8e9ee96af3540eb5a25786ce0b83c5a3c7d80a27d083092aa8e38f6d50380bcb86db8b4df268f1ded5a8ea

test:
  secret_key_base: daa4b24beb4ecdc0dc7f2ccb4877e00802d28fe0f688db36eb650f42a66ff168c8268eaa37223575cfe7bf49174f25eb8527bbf3194e4e9be9912e96a91f1783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
